# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Testing stuff

on:
  workflow_dispatch:
    inputs:
      entry:
        description: 'Some random text'
        required: false
        default: 'Lorem Ipsum 🚀, and hello world!!!'

jobs:
  test_branches:
    name: Test branch
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            FULL_BRANCH_NAME=${{ github.head_ref }}
          else
            FULL_BRANCH_NAME=$(basename ${{ github.ref }})
          fi
          echo "FULL_BRANCH_NAME=$FULL_BRANCH_NAME" >> "$GITHUB_OUTPUT"
      - name: Sanitize name
        id: sanitized-name
        run: |
          FULL_BRANCH_NAME="${{ steps.branch-name.outputs.FULL_BRANCH_NAME }}"

          SANITIZED_BRANCH_NAME=$(echo "$FULL_BRANCH_NAME" | tr -c '[:alnum:]\n' '-')
          echo "SANITIZED_BRANCH_NAME=$SANITIZED_BRANCH_NAME"

          LOCAL_VARIABLE=${{ inputs.entry }}
          LOCAL_SANITIZED_VARIABLE=$(echo "$LOCAL_VARIABLE" | tr -c '[:alnum:]\n' '-')
          echo "$LOCAL_SANITIZED_VARIABLE"