# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Pull Request

on: pull_request

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  install:
    name: Install project
    uses: ./.github/workflows/install.yaml

  prettier:
    name: Run prettier
    needs: [install]
    uses: ./.github/workflows/prettier.yaml
    with:
      cache_id: ${{ needs.install.outputs.install_cache_id }}