# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Pull Request

on: pull_request

concurrency:
  group: pull-request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: Install project
    uses: ./.github/workflows/install.yml
