# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Prettier - review dog

on: pull_request

concurrency:
  group: review-dog-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
